version: "3.7"
services:
  web:
    container_name: web
    image: nginx:1.21-alpine
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/app:cached
      - ./infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
    links:
      - app
    depends_on:
      - app

  app:
    container_name: app
    build:
      context: ./infrastructure/php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/app:cached
    working_dir: /var/www/app

  composer:
    container_name: composer
    build:
      context: ./infrastructure/composer
      dockerfile: Dockerfile
    volumes:
      - ./src:/src
    working_dir: /src
