version: "3.7"
services:
  web:
    container_name: web
    image: nginx:1.21-alpine
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/app:cached
      - ./infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
    links:
      - app
    depends_on:
      - app
    networks:
      internal-network:

  app:
    container_name: app
    build:
      context: ./infrastructure/php
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/app:cached
      - ./infrastructure/php/dev/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:cached
    working_dir: /var/www/app
    networks:
      internal-network:

  db:
    image: mysql:5.7
    container_name: db
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: storage
    volumes:
      - ./infrastructure/mysql/my.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./infrastructure/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - storage-data:/var/lib/mysql:cache
    stop_grace_period: 1m
    networks:
      internal-network:

  composer:
    container_name: composer
    build:
      context: ./infrastructure/composer
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
    working_dir: /backend

networks:
  internal-network:
    driver: bridge

volumes:
  storage-data:
    driver: local
